# Generated by Django 3.2.5 on 2021-08-30 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255)),
                ('article_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('article_content', models.TextField()),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('article_date_posted', models.DateTimeField(auto_now_add=True)),
                ('article_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('article_totalViewCount', models.IntegerField(default=0)),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('article_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.articlecategorymodel')),
            ],
        ),
    ]
